import createClient from "openapi-fetch";

import type { operations, paths } from "../types/api-schema"; // generated by openapi-typescript
import { API_URL } from "@/constants";
import { supabase } from "@/hooks/use-auth";

export type Message = operations['getApiHistoryByConversationId']['responses']['200']['content']['application/json'][number];

export const apiClient = createClient<paths>({ baseUrl: API_URL})


type WithAccessTokenCallback<T> = (options: {
  headers: Record<string, string>;
}) => Promise<T>;

export const withAccessToken=async<T>(callback:WithAccessTokenCallback<T> )=>{
     const session = (await supabase.auth.getSession()).data.session;

  const token = session?.access_token;
  if (!token) {
    // throw new Error("Not authenticated");
    console.log("no token")
  }

  return callback({
    headers: {
      Authorization: `Bearer ${token}`,
    },
  });
}
