import createClient from "openapi-fetch";

import type { operations, paths } from "../types/api-schema"; // generated by openapi-typescript
import { API_URL } from "@/constants";



export const apiClient = createClient<paths>({ baseUrl: API_URL });

export type Message = operations['getApiHistoryByConversationId']['responses']['200']['content']['application/json'][number];

export default apiClient